{% set name = "structout" %}
{% set version = "0.1.47" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structout-{{ version }}.tar.gz
  sha256: c5c5493e6389c97c19082c645c70ddeb8128a912fe43a418fb26bb166cb4003b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - networkx
    - python >=3.8
    - scipy
    - sty

test:
  imports:
    - structout
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smautner/StructOut_py3
  summary: pretty print data structures
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
